# Generated by Django 2.2.17 on 2021-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeee5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.BigIntegerField()),
                ('second', models.BooleanField()),
            ],
        ),
    ]
